// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI_BookStore.Data;

#nullable disable

namespace MinimalAPI_BookStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI_BookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Description = "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
                            Genre = "Classic",
                            IsAvailable = true,
                            Title = "The Great Gatsby",
                            Year = new DateTime(1925, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Description = "The story of racial injustice and the loss of innocence in a Southern town.",
                            Genre = "Fiction",
                            IsAvailable = true,
                            Title = "To Kill a Mockingbird",
                            Year = new DateTime(1960, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Description = "A dystopian novel set in a totalitarian society ruled by the Party and its leader, Big Brother.",
                            Genre = "Science Fiction",
                            IsAvailable = true,
                            Title = "1984",
                            Year = new DateTime(1949, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Description = "The romantic entanglements of the Bennet sisters in early 19th century England.",
                            Genre = "Romance",
                            IsAvailable = true,
                            Title = "Pride and Prejudice",
                            Year = new DateTime(1813, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            Description = "The adventure of Bilbo Baggins as he sets out on a quest to help a group of dwarves reclaim their homeland.",
                            Genre = "Fantasy",
                            IsAvailable = true,
                            Title = "The Hobbit",
                            Year = new DateTime(1937, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
